modLoader = "javafml"
loaderVersion = "[36,)"
license = "GPL-3.0 License"
license="https://raw.githubusercontent.com/devs-immortal/The-Aether/master/LICENSE.md"
issueTrackerURL="https://github.com/devs-immortal/The-Aether/issues"


[[mods]]
modId = "the_aether"
version = "${version}"
displayName = "The Aether"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/the-aether"
credits = "Credits go to Gilded Games for maintaining the Aether mod, the Aether Collaboration Team (Kingbdogz, Shockah, Kodaichi, Flan, and 303) for creating the original Aether mod, Modding Legacy (115kino, KingPhygieBoo, and Lachney) for originally porting and developing the mod in newer versions, and GitHub contributors for their help throughout development. InsomniaKitten is also credited with providing the inventory texture."
authors = "kalucky0, Azazelthedemonlord, bconlon, Oscar Payn, Hugo Payn, JellySquid, Calum Henderson (diabolical17), Karanomuro, 24Chrome"
description = '''
    The Aether is a dimension high in the sky composed of floating islands. Ascend through a Glowstone portal and begin a new survival adventure packed with new ores, mythical creatures and perilous Dungeons. All you need to do is build a Glowstone frame and add water to light the mystical portal, step in and you'll be transported immediately to the luscious hostile paradise known as the Aether.'''

[[dependencies.aether]]
    modId = "forge"
    mandatory = true
    versionRange = "[36,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.17]"
    ordering = "NONE"
    side = "BOTH"